### ISSUE TITLE
Ubuntu / LibreOffice 7.3.0.3 / ElementTree.ParseError: no element found

### ISSUE THREAD

**Issue by johnjohndoe** [vmiklos/ged2dot#201] opened 2022-02-15 22:20 UTC
**Environment**
- Ubuntu 20.04.3
- LibreOffice 7.3.0.3
- [Extension 7.3](https://github.com/vmiklos/ged2dot/releases/tag/v7.3)

**Reproducer steps**
1. Open https://raw.githubusercontent.com/blokhin/genealogical-trees/master/data/tsars.ged with LibreOffice

**Actual result**
- Pop-up appears: `General input/output error.`
- Console output:
``` python
failed at node 1429[0]
dot: maze.c:311: chkSgraph: Assertion `np->cells[0]' failed.
Traceback (most recent call last):
  File "/home/john/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu429500spycr.tmp_/gedcom-7.3.oxt/importer.py", line 125, in filter
    buf = self.__to_svg(path)
  File "/home/john/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu429500spycr.tmp_/gedcom-7.3.oxt/importer.py", line 103, in __to_svg
    inlineize.inlineize(noinline, inline)
  File "/home/john/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu429500spycr.tmp_/gedcom-7.3.oxt/inlineize.py", line 25, in inlineize
    tree.parse(from_path)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

**Expected behavior**
- Some nice rendering.

**Comment by vmiklos** [comment] 2022-02-25 21:04
Running that input from the cmdline also fails:

```
$ ./ged2dot.py --input workdir/gh201/tsars.ged --output test.dot
Traceback (most recent call last):
  File "./ged2dot.py", line 658, in <module>
    main()
  File "./ged2dot.py", line 654, in main
    convert(config.get_dict())
  File "./ged2dot.py", line 620, in convert
    root_family = graph_find(graph, config["rootfamily"])
  File "./ged2dot.py", line 117, in graph_find
    assert len(results) == 1
AssertionError
```

Let me see what can be done with that.

**Comment by vmiklos** [comment] 2022-03-04 21:55
Getting back to this, the actual .ged opening in LO works fine for me. What version of graphviz do you have?

> failed at node 1429[0]
> dot: maze.c:311: chkSgraph: Assertion `np->cells[0]' failed.

This sounds like the underlying graphviz crashes for you, but not here.

First I get the popup to choose the root family:

![image](https://user-images.githubusercontent.com/13838/156846985-52ffcf53-7c81-4c4c-a9ef-99f779c8710c.png)

and if I accept the defaults, I get:

![image](https://user-images.githubusercontent.com/13838/156847073-93cb34fa-fda3-4049-b831-323c95e1726e.png)

Which looks reasonable.

```
$ dot -V
dot - graphviz version 2.40.1 (20161225.0304)
```

is what I have, what about you?

**Comment by johnjohndoe** [comment] 2022-03-04 23:51
> dot - graphviz version 2.43.0 (0)

**Comment by vmiklos** [comment] 2022-03-11 21:39
Hm, so either I feed different input to 'dot' or the newer 'dot' has a regression that my old 'dot' doesn't have.

Could you please run:

```
dot -Tsvg /path/to/in.txt
```

with this input: [in.txt](https://github.com/vmiklos/ged2dot/files/8235885/in.txt) and see if that still crashes? Thanks.

**Comment by johnjohndoe** [comment] 2022-03-11 21:54
Here is the tail of the shell output:

```
Warning: No such file or directory while opening /home/vmiklos/git/libreoffice/lo73/opt/UserInstallation/user/uno_packages/cache/uno_packages/lu29209t3uuuw.tmp_/gedcom-v7.3-5-gea76fe8.oxt/marriage.svg
Error: No or improper image file="/home/vmiklos/git/libreoffice/lo73/opt/UserInstallation/user/uno_packages/cache/uno_packages/lu29209t3uuuw.tmp_/gedcom-v7.3-5-gea76fe8.oxt/marriage.svg"
in label of node 43
Warning: No such file or directory while opening /home/vmiklos/git/libreoffice/lo73/opt/UserInstallation/user/uno_packages/cache/uno_packages/lu29209t3uuuw.tmp_/gedcom-v7.3-5-gea76fe8.oxt/marriage.svg
Error: No or improper image file="/home/vmiklos/git/libreoffice/lo73/opt/UserInstallation/user/uno_packages/cache/uno_packages/lu29209t3uuuw.tmp_/gedcom-v7.3-5-gea76fe8.oxt/marriage.svg"
in label of node 54
failed at node 1429[0]
dot: maze.c:311: chkSgraph: Assertion `np->cells[0]' failed.
[1]    146025 abort (core dumped)  dot -Tsvg in.txt
```

**Comment by vmiklos** [comment] 2022-03-18 22:35
Really strange. Here is what I tried:

1) https://gitlab.com/graphviz/graphviz seems to not contain a tag named "2.43.0"
2) https://packages.ubuntu.com/search?keywords=graphviz&searchon=names&suite=focal&section=all seems to ship 2.42.2
3) I built 2.42.2 from git, but still can't reproduce your crash, even looked at Makefiles and seems nobody specified -DNDEBUG to disable assert() calls.

I wonder if it makes sense to continue tracking down your bug or just close this and you are free to re-report this to graphviz?

In general, I would like to see them fix the root cause, rather than work something around in ged2dot.

**Comment by johnjohndoe** [comment] 2022-03-18 22:56
Thanks for the effort! I would also think that you should not invest more time.
I quickly checked that `dot` is symlinked to `/usr/sbin/libgvc6-config-update` if this helps anyhow. I can't say where version 2.43.0 comes from. It might originate from some PPA I have added. No idea how to track this down.

**Closed** 2022-03-18 23:30 UTC
Labels: need-info
