### ISSUE TITLE
siblings are printed even with MaxSiblingDepth and MaxSiblingFamilyDepth = 0

### ISSUE THREAD

**Issue by dougstarfish** [vmiklos/ged2dot#17] opened 2019-12-30 03:40 UTC
Leaving this open since it makes family trees too big to print after about depth =5 when siblings are present. 

The problem seems to be in buildSubGraph since it doesn't differentiate between siblings and direct descendant hierarchies.

Not sure what the best fix is, but perhaps something along the lines of filterFamilies going up could keep the tree and then buildSubGraph could use this information to filter out siblings.

**Comment by vmiklos** [comment] 2019-12-30 13:51
One obvious thing to try: did you check if =0 means literally "limit as much as possible", not "infinite"? I.e. does =1 make a difference?

Other than that, could you please attach a reproducer .ged, with some description of what is the actual and expected result? I assume what you ask for is reasonably straightforward to do, I just don't have the code swapped in my brain, given I wrote most of this ~6 years ago. :-)

**Comment by dougstarfish** [comment] 2020-01-06 01:57
Holidays kept me busy, but here's a simple family tree that I built to show that siblings are displayed no matter what (or so it seems). At the very least, Greg shouldn't show up, though I can understand starting with a family will show all of those siblings; Greg isn't part of F1 which is the starting family.

0 HEAD
0 @P1@ INDI 
1 NAME Alice /A/
1 SEX F
1 FAMS @F1@
1 FAMC @F2@
0 @P2@ INDI 
1 NAME Bob /B/
1 SEX M
1 FAMS @F1@
0 @P3@ INDI
1 NAME Casey /C/
1 SEX M
1 FAMS @F1@
0 @P4@ INDI
1 NAME Alex /A/
1 SEX M
1 FAMS @F1@
0 @P5@ INDI
1 NAME Tracy /T/
1 SEX M
1 FAMS @F1@
0 @P6@ INDI
1 NAME Billy /B/
1 SEX F
1 FAMC @F1@
0 @P7@ INDI
1 NAME Margert /M/
1 SEX F
1 FAMS @F2@
0 @P8@ INDI
1 NAME William /W/
1 SEX M
1 FAMS @F2@
0 @P9@ INDI 
1 NAME Greg /G/
1 SEX M
1 FAMC @F2@
0 @F1@ FAM 
1 HUSB @P2@
1 WIFE @P1@
1 CHIL @P3@
1 CHIL @P4@
1 CHIL @P5@
1 CHIL @P6@
0 @F2@ FAM
1 HUSB @P8@
1 WIFE @P7@
1 CHIL @P1@
1 CHIL @P9@
0 TRLR

**Comment by vmiklos** [comment] 2020-01-17 13:01
Ah yes, I see the problem. If you read the doc of those config keys:

> layoutMaxSiblingDepth: Number of ancestor generations, where also sibling spouses are shown.

and

> layoutMaxSiblingFamilyDepth: Number of ancestor generations, where also sibling families are shown.

So even if you set these to 0, they only influence ancestor generations, not the generation of the root family. I'll add a separate config option for this, since altering the meaning of the existing ones would be confusing, but the use-case makes sense to me.

**Comment by vmiklos** [comment] 2020-01-17 20:19
Greg goes away when the new option is used, see the testcase -> closing. Thanks for the nice minimal reproducer sample!

**Closed by vmiklos** 2020-01-17 20:19 UTC
Labels: enhancement
