### ISSUE TITLE
Root family not recognized and can't enter rootfamily in GUI options

### ISSUE THREAD

**Issue by slashdottir** [vmiklos/ged2dot#265] opened 2023-10-04 03:40 UTC
**Reproducer steps**
1. First step

Try running from command line

```
$ ./ged2dot.py --input ./greg-family-tree.ged --output test.dot --rootfamily "F594" --familydepth 3
Traceback (most recent call last):
  File "/Users/foo/src/ancestry/ged2dot/./ged2dot.py", line 692, in <module>
    main()
  File "/Users/foo/src/ancestry/ged2dot/./ged2dot.py", line 688, in main
    convert(config.get_dict())
  File "/Users/foo/src/ancestry/ged2dot/./ged2dot.py", line 653, in convert
    raise ValueError(reason)
ValueError: Root family 'F594' is not found.
```

If I understand correctly, the rootfamily code can be found in the ged file next to the code FAMS

This GED file came from ancestry.com if it matters

afaict, my code is F594

```
grep FAMS greg-family-tree.ged 
1 FAMS @F594@
1 FAMS @F594@
...
```

2. Second step: Install the app and try that
  Download installer for Mac OS 64 bit
  Run app. There is no way to enter a value for Root Family. There is only an empty dropdown
   
<img width="393" alt="image" src="https://github.com/vmiklos/ged2dot/assets/47145634/c4325c3b-5286-438b-a6cd-3aa65275bdfe">

 Press OK. An error is displayed that the root family cannot be none
<img width="344" alt="image" src="https://github.com/vmiklos/ged2dot/assets/47145634/04118c8c-c7b3-4eff-856a-a62c914eb881">

**Expected behavior**

I should be able to parse my family tree hopefully

I also tried downloading the source and running it in Pycharm, however I'm unable to install pygraphviz there for some reason as it can't seem to find the pycharmviz/clang.h file no matter how many paths I add, but that's a side issue

**Comment by vmiklos** [comment] 2023-10-04 19:27
Hi,

Your command-line invocation looks reasonable. Ancestry.com is fine, I also use it for my own family tree, together with its gedcom export.

Could you try if

```
./ged2dot.py --input tests/happy.ged --output test.dot --rootfamily F1 --familydepth 3
```

works for you? If so, then we need to understand what is the difference between happy.ged and your actual gedcom input that breaks. FWIW I just exported my own tree from ancestry.com, and I can't see an obvious problem.

Could you try anonymizing your problematic input (search&replace with a text editor to get rid of sensitive data) so it can be attached here?

Thanks.

**Comment by slashdottir** [comment] 2023-10-04 19:55
If I put F1 for rootfamily it complains that F1 was not found of course.  I will anonymize and post back later today. Thank you!

**Comment by slashdottir** [comment] 2023-10-05 22:13
I'm having a hard time anonymizing this. My huge tree has over 59k entries.  Still working on it.

**Comment by vmiklos** [comment] 2023-10-16 19:01
Although it's not ideal, if you have trouble anonymizing your input data, perhaps send the problematic file to me via email and I'll try to see how to construct a simple public reproducer for the problem you run into. As you like.

**Comment by vmiklos** [comment] 2023-12-17 20:16
Closing since no reproducer (public or private) in 2 months. Feel free to reopen.

**Closed** 2023-12-17 20:16 UTC
